"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const sphero_mini_1 = require("./toys/sphero-mini");
exports.SpheroMini = sphero_mini_1.SpheroMini;
const lightning_mcqueen_1 = require("./toys/lightning-mcqueen");
exports.LightningMcQueen = lightning_mcqueen_1.LightningMcQueen;
const bb9e_1 = require("./toys/bb9e");
exports.BB9E = bb9e_1.BB9E;
const r2d2_1 = require("./toys/r2d2");
exports.R2D2 = r2d2_1.R2D2;
